name: sjpl
entry_urls:
  - https://events.sjpl.org/events
type: dynamic
selectors:
  items: ".event-card"
  fields:
    title: ".event-title"
    date: ".event-date"
    time: ".event-time"
    description: ".event-description"
    url: ".event-title a::attr(href)"